---
title: "Mémoire Time Series"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Données

```{r, fig.height=3, fig.width=8, message=FALSE, warning=FALSE}
library(ggplot2) ; theme_set(theme_bw())
d <- read.csv(file="electricite_2.csv",header=TRUE) 
#d <- t(d)
#summary(d)
dim(d['Production.totale.brute.d.electricite..en.GWh.'])
column <- d['Production.totale.brute.d.electricite..en.GWh.']
ts2 <- ts(column[1:length(t(column)), 1], frequency = 12)
prod.tot <- ts(d['Production.totale.brute.d.electricite..en.GWh.'], frequency = 12)
plot(prod.tot)

decompose.prod.tot <- decompose(prod.tot, "additive")
#stl.prod.tot <- stl(d['Production.totale.brute.d.electricite..en.GWh.'],"periodic",1,NULL)
plot(decompose.prod.tot)
rand <- na.omit(decompose.prod.tot$random)
acf(prod.tot)
acf(rand)

plot(prod.tot)
plot(diff(prod.tot))
plot(acf(diff(prod.tot)))
plot(diff(diff(prod.tot)))
plot(acf(diff(diff(prod.tot))))
plot(diff(diff(diff(prod.tot))))

summary(prod.tot)
```

```{r}
#stl.prod.tot <- stl(prod.tot,s.window = "periodic",s.degree = 1)
library(tseries)
library(forecast)
prod.tot.adjusted <- prod.tot - decompose.prod.tot$seasonal
plot(prod.tot.adjusted)
prod.tot.adjusted.diff <- diff(prod.tot.adjusted)
plot(prod.tot.adjusted.diff)

prod.tot.diff <- diff(prod.tot)
acf(prod.tot.diff)
pacf(prod.tot.diff)

#Test de Dickey-Fuller de racine unitaire
adf.test(prod.tot.adjusted.diff, alternative="stationary")
adf.test(diff(prod.tot), alternative="stationary")

acf(prod.tot.adjusted.diff)
pacf(prod.tot.adjusted.diff)

auto.arima(prod.tot.adjusted.diff, max.Q = 5, ic="bic", trace = T, stationary = T)
```

```{r}
arima(prod.tot.adjusted.diff, order=c(1,0,1), include.mean = F)
```

La p-value du test étant inférieure à 0.05, on rejette l'hypothèse nulle : la série désaisonnalisée et différenciée une fois est bien stationnaire. 
Remarque : aussi vrai si on n'a pas désaisonnalisé avant ! 


```{r}
holt.winters <- HoltWinters(prod.tot)
plot(holt.winters)
plot(forecast(holt.winters, h = 12))
```
```{r}
stl.prod.tot <- stl(ts2, s.window = 24)
plot(stl.prod.tot)
  ```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
